.TH GLADE2SCRIPT 1 "February 2012" Linux "User Manuel"
.SH NAME
Glade2script \- Glade interface engine for scripts
.SH SYNOPSIS
.B glade2script
[
.B --glade
file.glade ] [
.B options
] ...
.SH DESCRIPTION
Glade2script allows a script (Bash, Python or other) to display and
interact with a GUI (created with Glade).
.br
Most of the opportunities offered by Gtk are available. A terminal
(vte) and/or webkit are integrable. One can also embed an external
application that supports it natively, like mplayer or gvim. A plugin
system was added to extend G2S capability.
.br
Documentation, many examples, and an interface giving access to the
archive supports (simply install and run glade2script-doc).
.br
Glade2script is already used by several softwares, such as Boot-Repair,
OS-Uninstaller, Debeditor, DeskWall, GUnity, LaunchBash, Malokal,
mkv_extractor_gui, Screencastor, Sylaba2, Xee, Zenitor.
.br
This package contains the executable of the Gtk3 version.
.SH AUTHORS
Ansuz Peorth <ansuzpeorth@gmail.com>
.SH SEE ALSO
.B https://launchpad.net/glade2script
.br
.B http://glade2script.tuxfamily.org/
.br
.B http://code.google.com/p/glade2script/
